// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Crud Goswagger
//
//	Crud Goswagger.
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /
//	Version: 1.0.0
//	License: Apache 2.0 https://www.apache.org/licenses/LICENSE-2.0
//	Contact: Crud Goswagger<CrudGoswagger@email.com> http://localhost:8080/docs
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
