// Code generated by go-swagger; DO NOT EDIT.

package apis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Crud Goswagger.",
    "title": "Crud Goswagger",
    "contact": {
      "name": "Crud Goswagger",
      "url": "http://localhost:8080/docs",
      "email": "CrudGoswagger@email.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    },
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/health": {
      "get": {
        "tags": [
          "health check"
        ],
        "summary": "check server",
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "baseRequest": {
      "type": "object"
    },
    "baseResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Crud Goswagger.",
    "title": "Crud Goswagger",
    "contact": {
      "name": "Crud Goswagger",
      "url": "http://localhost:8080/docs",
      "email": "CrudGoswagger@email.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    },
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/health": {
      "get": {
        "tags": [
          "health check"
        ],
        "summary": "check server",
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "baseRequest": {
      "type": "object"
    },
    "baseResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
